version: '3.9'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/Rebel_Assignment
    restart: always
    networks:
      - Rebel_Assignment
    container_name: frontend

  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/Rebel_Assignment
    restart: always
    networks:
      - Rebel_Assignment
    container_name: backend

networks:
  Rebel_Assignment:
    driver: bridge
